# 1. Database Setup
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.pfscwribwphpkbhxbwrm

# ??? ??! ?? ?? ?? ??? ????.
spring.datasource.password=${DB_PASSWORD}

# 2. JPA Setup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

# 3. Login Setup (??? ????!)
spring.security.user.name=user
spring.security.user.password=${APP_PASSWORD}

# 4. Port Setup
server.port=9090